# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            lockerfish
tagline:          tech bytes
url:              http://lockerfish.com
paginate:         1
baseurl:          /
author:
  name:           Hendrix Tavarez
  url:            https://twitter.com/htavarez
  email:          hendrix@lockerfish.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lockerfish/lockerfish.github.io
